/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shelby.carnet;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author shelby
 */
public final class Comptes extends javax.swing.JPanel {

    /**
     * Creates new form Comptes
     */
    //propriétés
    private String[] listeInfos;
    private int id;
    public Comptes(String [] liste, int ni) {
        setVisible(true);
        initComponents();
        setListeInfos(liste);
        setId(ni);
       colorierIdPair();
       afficheInfos();
    }
    
    //Methode d'accès en ecriture

    public void setId(int tmp) {
        this.id = tmp;
    }
    public void setListeInfos(String[] tmp) {
        this.listeInfos = tmp;
    }
    
    
    //Méthode d'accès en lecture
    public int getId() {
        return id;
    } 
    public String[] getListeInfos() {
        return listeInfos;
    }
    
    /**
     * La methode afficheInfos() nous permet d'afficher le
     * nom du compte et l'utilisateur ainsi que sa photo.
     */
    private void afficheInfos(){
        nomCompteLbl.setText(listeInfos[0]);
        utilisateurCompteLbl.setText(listeInfos[1]);
        affichePhotos();
    }
    
     private void affichePhotos() {
       //Creer un icon
      ImageIcon iconPhotos = new ImageIcon(listeInfos[2]);
      //Transformer l'icone en image
      Image  uneImage = iconPhotos.getImage();
      //reduire la taille de l'image de 50%
      uneImage = uneImage.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
      //transformer l'image en Icon
      iconPhotos.setImage(uneImage);
      photosLbl.setIcon(iconPhotos);
     }
    
     
     
       private void setCouleur(JLabel tmp){
      tmp.setBackground(Color.white);
      tmp.setOpaque(true);
  } 
  
  private void colorierIdPair(){
      if(id %  2 == 0){
          setCouleur(nomCompteLbl);
          setCouleur(utilisateurCompteLbl);
          setCouleur(photosLbl);
      }
  }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photosLbl = new javax.swing.JLabel();
        nomCompteLbl = new javax.swing.JLabel();
        utilisateurCompteLbl = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(390, 50));
        setMinimumSize(new java.awt.Dimension(390, 50));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(380, 50));
        setLayout(new java.awt.GridLayout(1, 0));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.shelby.carnet.CarnetApp.class).getContext().getResourceMap(Comptes.class);
        photosLbl.setText(resourceMap.getString("photosLbl.text")); // NOI18N
        photosLbl.setName("photosLbl"); // NOI18N
        add(photosLbl);

        nomCompteLbl.setFont(new java.awt.Font("LM Roman Dunhill 10", 0, 24)); // NOI18N
        nomCompteLbl.setForeground(new java.awt.Color(12, 119, 196));
        nomCompteLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomCompteLbl.setText(resourceMap.getString("nomCompteLbl.text")); // NOI18N
        nomCompteLbl.setName("nomCompteLbl"); // NOI18N
        add(nomCompteLbl);

        utilisateurCompteLbl.setFont(new java.awt.Font("LM Roman Dunhill 10", 1, 18)); // NOI18N
        utilisateurCompteLbl.setForeground(new java.awt.Color(0, 0, 153));
        utilisateurCompteLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        utilisateurCompteLbl.setText(resourceMap.getString("utilisateurCompteLbl.text")); // NOI18N
        utilisateurCompteLbl.setName("utilisateurCompteLbl"); // NOI18N
        add(utilisateurCompteLbl);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nomCompteLbl;
    private javax.swing.JLabel photosLbl;
    private javax.swing.JLabel utilisateurCompteLbl;
    // End of variables declaration//GEN-END:variables

   
}
