/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shelby.carnet.carnetUtils;

import carnet.CarnetApp;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author shelby
 */
public class EndInstall extends javax.swing.JFrame {
private boolean choix = true;
    /**
     * Creates new form End
     */
    public EndInstall() {
        initComponents();
        centerEcran("Finished");
        grpBtn.add(noBtn);
        grpBtn.add(yesBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpBtn = new javax.swing.ButtonGroup();
        endTitleLbl = new javax.swing.JLabel();
        openCarnetLbl = new javax.swing.JLabel();
        yesBtn = new javax.swing.JRadioButton();
        noBtn = new javax.swing.JRadioButton();
        validerBtn = new javax.swing.JButton();
        infosPnl = new javax.swing.JPanel();
        verionInfosLbl = new javax.swing.JLabel();
        fabricantInfosLbl = new javax.swing.JLabel();
        endFondlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        endTitleLbl.setFont(new java.awt.Font("LM Roman Dunhill 10", 1, 26)); // NOI18N
        endTitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(carnet.CarnetApp.class).getContext().getResourceMap(EndInstall.class);
        endTitleLbl.setText(resourceMap.getString("endTitleLbl.text")); // NOI18N
        endTitleLbl.setName("endTitleLbl"); // NOI18N
        getContentPane().add(endTitleLbl);
        endTitleLbl.setBounds(90, 30, 240, 50);

        openCarnetLbl.setFont(new java.awt.Font("LM Roman Dunhill 10", 1, 18)); // NOI18N
        openCarnetLbl.setForeground(new java.awt.Color(255, 255, 255));
        openCarnetLbl.setText("Open your Diary:"); // NOI18N
        openCarnetLbl.setName("openCarnetLbl"); // NOI18N
        getContentPane().add(openCarnetLbl);
        openCarnetLbl.setBounds(60, 140, 142, 22);

        yesBtn.setFont(new java.awt.Font("LM Roman Dunhill 10", 0, 18)); // NOI18N
        yesBtn.setForeground(new java.awt.Color(255, 255, 255));
        yesBtn.setText(resourceMap.getString("yesBtn.text")); // NOI18N
        yesBtn.setToolTipText(resourceMap.getString("yesBtn.toolTipText")); // NOI18N
        yesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        yesBtn.setName("yesBtn"); // NOI18N
        yesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(yesBtn);
        yesBtn.setBounds(230, 140, 52, 24);

        noBtn.setFont(new java.awt.Font("LM Roman Dunhill 10", 0, 18)); // NOI18N
        noBtn.setForeground(new java.awt.Color(255, 255, 255));
        noBtn.setText(resourceMap.getString("noBtn.text")); // NOI18N
        noBtn.setToolTipText(resourceMap.getString("noBtn.toolTipText")); // NOI18N
        noBtn.setName("noBtn"); // NOI18N
        noBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBtnActionPerformed(evt);
            }
        });
        getContentPane().add(noBtn);
        noBtn.setBounds(300, 140, 46, 24);

        validerBtn.setFont(new java.awt.Font("LM Roman Dunhill 10", 0, 19)); // NOI18N
        validerBtn.setText("Accept"); // NOI18N
        validerBtn.setToolTipText("Choice validation"); // NOI18N
        validerBtn.setName("validerBtn"); // NOI18N
        validerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(validerBtn);
        validerBtn.setBounds(230, 180, 100, 33);

        infosPnl.setFont(new java.awt.Font("LM Roman Dunhill 10", 0, 15)); // NOI18N
        infosPnl.setName("infosPnl"); // NOI18N
        infosPnl.setOpaque(false);

        verionInfosLbl.setFont(new java.awt.Font("LM Roman Dunhill 10", 0, 15)); // NOI18N
        verionInfosLbl.setForeground(new java.awt.Color(255, 255, 255));
        verionInfosLbl.setText(resourceMap.getString("verionInfosLbl.text")); // NOI18N
        verionInfosLbl.setName("verionInfosLbl"); // NOI18N

        fabricantInfosLbl.setFont(new java.awt.Font("LM Roman Dunhill 10", 0, 15)); // NOI18N
        fabricantInfosLbl.setForeground(new java.awt.Color(255, 255, 255));
        fabricantInfosLbl.setText(resourceMap.getString("fabricantInfosLbl.text")); // NOI18N
        fabricantInfosLbl.setName("fabricantInfosLbl"); // NOI18N

        javax.swing.GroupLayout infosPnlLayout = new javax.swing.GroupLayout(infosPnl);
        infosPnl.setLayout(infosPnlLayout);
        infosPnlLayout.setHorizontalGroup(
            infosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infosPnlLayout.createSequentialGroup()
                .addComponent(verionInfosLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(fabricantInfosLbl)
                .addContainerGap())
        );
        infosPnlLayout.setVerticalGroup(
            infosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infosPnlLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(infosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verionInfosLbl)
                    .addComponent(fabricantInfosLbl)))
        );

        getContentPane().add(infosPnl);
        infosPnl.setBounds(0, 240, 440, 40);

        endFondlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shelby/carnet/carnetUtils/resources/fondLogin.jpg"))); // NOI18N
        endFondlbl.setName("endFondlbl"); // NOI18N
        getContentPane().add(endFondlbl);
        endFondlbl.setBounds(0, 0, 440, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtnActionPerformed
        choix = true;
    }//GEN-LAST:event_yesBtnActionPerformed

    private void noBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBtnActionPerformed
      choix = false;
    }//GEN-LAST:event_noBtnActionPerformed

    private void validerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerBtnActionPerformed
       if(choix){
            dispose();
            CarnetApp carnet = new CarnetApp();
            carnet.runApp(); 
        }else{
            System.exit(0); 
        }
    }//GEN-LAST:event_validerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EndInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EndInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EndInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EndInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EndInstall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel endFondlbl;
    private javax.swing.JLabel endTitleLbl;
    private javax.swing.JLabel fabricantInfosLbl;
    private javax.swing.ButtonGroup grpBtn;
    private javax.swing.JPanel infosPnl;
    private javax.swing.JRadioButton noBtn;
    private javax.swing.JLabel openCarnetLbl;
    private javax.swing.JButton validerBtn;
    private javax.swing.JLabel verionInfosLbl;
    private javax.swing.JRadioButton yesBtn;
    // End of variables declaration//GEN-END:variables

    private void centerEcran(String title) {
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension dimensionEcran = kit.getScreenSize();
        int largeur = dimensionEcran.width;
        int hauteur = dimensionEcran.height;
        setTitle(title);
        setBounds((largeur-440)/2,(hauteur-310)/2, 440,310);
        setResizable(false);
    }
}
