/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Contacts.java
 * 
 */

package icebook;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Patrick-Noah
 */
public final class Contacts extends javax.swing.JPanel {
    
    private String [] listeInfos;
    private int id;

    /** Creates new form Contact
     * @param liste
     * @param ni */

    public Contacts(String [] liste, int ni) {
        setVisible(true);
        initComponents();
        setListeInfos(liste);
        setId(ni); 
        colorierIdPair();
        afficheInfos();
    }


     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoLbl = new javax.swing.JLabel();
        prenomLbl = new javax.swing.JLabel();
        nomLbl = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(390, 50));
        setMinimumSize(new java.awt.Dimension(390, 50));
        setPreferredSize(new java.awt.Dimension(380, 50));
        setRequestFocusEnabled(false);

        prenomLbl.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        prenomLbl.setForeground(new java.awt.Color(0, 0, 153));
        prenomLbl.setText("prénom");

        nomLbl.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        nomLbl.setForeground(new java.awt.Color(0, 0, 153));
        nomLbl.setText("nom");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(photoLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(prenomLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(nomLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(photoLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(prenomLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(nomLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
  private String nom, prenom, url;
  
  private void afficheInfos(){
      prenomLbl.setText(listeInfos[0]);
      nomLbl.setText(listeInfos[1]);
      affichePhotos();
  }
  private  void affichePhotos(){
      //Creer un icon
      ImageIcon iconPhotos = new ImageIcon(listeInfos[2]);
      //Transformer l'icone en image
      Image  uneImage = iconPhotos.getImage();
      //reduire la taille de l'image de 50%
      uneImage = uneImage.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
      //transformer l'image en Icon
      iconPhotos.setImage(uneImage);
      photoLbl.setIcon(iconPhotos);
  }
  
  private void setCouleur(JLabel tmp){
      tmp.setBackground(Color.white);
      tmp.setOpaque(true);
  } 
  
  private void colorierIdPair(){
      if(id %  2 == 0){
          setCouleur(nomLbl);
          setCouleur(prenomLbl);
          setCouleur(photoLbl);
      }
  }
  
  

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nomLbl;
    private javax.swing.JLabel photoLbl;
    private javax.swing.JLabel prenomLbl;
    // End of variables declaration//GEN-END:variables

    public String[] getListeInfos() {
        return listeInfos;
    }

    public void setListeInfos(String[] listeInfos) {
        this.listeInfos = listeInfos;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

}
